use QLGiaoVien
go

--------1---------
SELECT HOTEN, LUONG
FROM GIAOVIEN
WHERE PHAI = N'Nữ'

--------2---------
SELECT HOTEN, LUONG * 1.1 AS 'LUONG TANG 10%'
FROM GIAOVIEN

--------3---------
SELECT DISTINCT GV.MAGV
FROM GIAOVIEN GV, BOMON BM
WHERE (GV.HOTEN LIKE N'Nguyễn%' AND GV.LUONG > 2000)
OR (YEAR(BM.NGAYNHANCHUC) >= 1995 AND BM.TRUONGBM = GV.MAGV)

--------4--------
SELECT GV.HOTEN
FROM GIAOVIEN GV, BOMON BM
WHERE BM.MAKHOA = 'CNTT' AND GV.MABM = BM.MABM

--------5---------
SELECT BM.MABM, BM.TENBM, GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV, BOMON BM
WHERE BM.TRUONGBM = GV.MAGV


--------6----------
SELECT GV.MAGV, BM.MABM, BM.TENBM
FROM GIAOVIEN GV, BOMON BM
WHERE GV.MABM = BM.MABM


---------7------------
SELECT DT.TENDT, GV.HOTEN AS 'GVCNDT'
FROM GIAOVIEN GV, DETAI DT
WHERE DT.GVCNDT = GV.MAGV


-----------8------------
SELECT KHOA.MAKHOA, GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV, KHOA
WHERE KHOA.TRUONGKHOA = GV.MAGV


-----------9--------------
SELECT  DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV, BOMON BM, THAMGIADT TG
WHERE TG.MADT = '006' AND TG.MAGV = GV.MAGV AND GV.MABM = 'VS'


-----------10---------------
SELECT DT.MADT, CHUDE.MACD, CHUDE.TENCD, GV.HOTEN, GV.NGSINH, GV.DIACHI
FROM GIAOVIEN GV, DETAI DT, CHUDE
WHERE DT.CAPQL = N'Nhà nước' AND DT.MACD = CHUDE.MACD AND DT.GVCNDT = GV.MAGV


------------11---------------
SELECT GV.HOTEN, GVQL.HOTEN
FROM GIAOVIEN GV, GIAOVIEN GVQL
WHERE GV.GVQLCM = GVQL.MAGV


------------12---------------
SELECT GV.HOTEN
FROM GIAOVIEN GV, GIAOVIEN GVQL
WHERE GVQL.HOTEN = N'Nguyễn An Trung' AND GV.GVQLCM = GVQL.MAGV


-------------13---------------
SELECT GV.HOTEN
FROM GIAOVIEN GV, BOMON BM
WHERE BM.TENBM = N'Hệ thống thông tin' AND BM.TRUONGBM = GV.MAGV


-------------14----------------
SELECT GV.HOTEN
FROM GIAOVIEN GV, DETAI DT, CHUDE
WHERE CHUDE.TENCD = N'Quản lý giáo dục' AND DT.MACD = CHUDE.MACD
	AND DT.GVCNDT = GV.MAGV


--------------15-----------------
SELECT CV.TENCV
FROM CONGVIEC CV, DETAI DT
WHERE DT.TENDT = N'HTTT quản lý các trường ĐH' AND CV.MADT = DT.MADT
	AND year(CV.NGAYBD) = 2008 AND MONTH(CV.NGAYBD) = 03


---------------16-----------------
SELECT GV.HOTEN, GVQL.HOTEN
FROM GIAOVIEN GV, GIAOVIEN GVQL
WHERE GV.GVQLCM = GVQL.MAGV


---------------17---------------
SELECT CV.MADT, CV.TENCV
FROM CONGVIEC CV
WHERE CV.NGAYBD BETWEEN '2007-01-01' AND '2007-08-01'


--------------18--------------
SELECT GV.HOTEN
FROM GIAOVIEN GV, GIAOVIEN TTH
WHERE TTH.HOTEN = N'Trần Trà Hương' AND GV.MABM = TTH.MABM AND GV.MAGV != TTH.MAGV


--------------19---------------
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV, BOMON BM, DETAI DT
WHERE DT.GVCNDT = GV.MAGV AND BM.TRUONGBM = GV.MAGV


--------------20----------------
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV, BOMON BM, KHOA
WHERE KHOA.TRUONGKHOA = GV.MAGV AND BM.TRUONGBM = GV.MAGV


--------------21------------------
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV, BOMON BM, DETAI DT
WHERE DT.GVCNDT = GV.MAGV AND BM.TRUONGBM = GV.MAGV


-------------22--------------------
SELECT DISTINCT GV.MAGV
FROM GIAOVIEN GV, KHOA, DETAI DT
WHERE DT.GVCNDT = GV.MAGV AND KHOA.TRUONGKHOA = GV.MAGV


--------------23-----------------
SELECT DISTINCT GV.MAGV
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MABM = 'HTTT' OR (TG.MADT = '001' AND TG.MAGV = GV.MAGV)


------------24-------------------
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV, GIAOVIEN TTH
WHERE TTH.MAGV = '002' AND GV.MABM = TTH.MABM AND GV.MAGV != '002'


-------------25--------------------
SELECT GV.HOTEN AS 'TRUONG BO MON'
FROM GIAOVIEN GV, BOMON BM
WHERE BM.TRUONGBM = GV.MAGV


--------------26------------------
SELECT HOTEN, LUONG
FROM GIAOVIEN